import type { Metadata } from "next"; 
import Header from "@/components/UI/header";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="mytheme">
      <body
        className={` antialiased`}
      >
        <div className="fit-center">
          <Header />
          {children}
        </div>

      </body>
    </html>
  );
}
